/*
Statuspage API

Testing IncidentPostmortemAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/sbecker59/statuspage-api-client-go/api/v1/statuspage"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_IncidentPostmortemAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test IncidentPostmortemAPIService DeletePagesPageIdIncidentsIncidentIdPostmortem", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var incidentId string

		httpRes, err := apiClient.IncidentPostmortemAPI.DeletePagesPageIdIncidentsIncidentIdPostmortem(context.Background(), pageId, incidentId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IncidentPostmortemAPIService GetPagesPageIdIncidentsIncidentIdPostmortem", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var incidentId string

		resp, httpRes, err := apiClient.IncidentPostmortemAPI.GetPagesPageIdIncidentsIncidentIdPostmortem(context.Background(), pageId, incidentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IncidentPostmortemAPIService PutPagesPageIdIncidentsIncidentIdPostmortem", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var incidentId string

		resp, httpRes, err := apiClient.IncidentPostmortemAPI.PutPagesPageIdIncidentsIncidentIdPostmortem(context.Background(), pageId, incidentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IncidentPostmortemAPIService PutPagesPageIdIncidentsIncidentIdPostmortemPublish", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var incidentId string

		resp, httpRes, err := apiClient.IncidentPostmortemAPI.PutPagesPageIdIncidentsIncidentIdPostmortemPublish(context.Background(), pageId, incidentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IncidentPostmortemAPIService PutPagesPageIdIncidentsIncidentIdPostmortemRevert", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var incidentId string

		resp, httpRes, err := apiClient.IncidentPostmortemAPI.PutPagesPageIdIncidentsIncidentIdPostmortemRevert(context.Background(), pageId, incidentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
