/*
Statuspage API

Testing UsersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/sbecker59/statuspage-api-client-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_UsersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test UsersAPIService DeleteOrganizationsOrganizationIdUsersUserId", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var organizationId string
		var userId string

		resp, httpRes, err := apiClient.UsersAPI.DeleteOrganizationsOrganizationIdUsersUserId(context.Background(), organizationId, userId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsersAPIService GetOrganizationsOrganizationIdPermissionsUserId", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var organizationId string
		var userId string

		resp, httpRes, err := apiClient.UsersAPI.GetOrganizationsOrganizationIdPermissionsUserId(context.Background(), organizationId, userId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsersAPIService GetOrganizationsOrganizationIdUsers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var organizationId string

		resp, httpRes, err := apiClient.UsersAPI.GetOrganizationsOrganizationIdUsers(context.Background(), organizationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsersAPIService PostOrganizationsOrganizationIdUsers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var organizationId string

		resp, httpRes, err := apiClient.UsersAPI.PostOrganizationsOrganizationIdUsers(context.Background(), organizationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
