/*
Statuspage API

Testing StatusEmbedConfigAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/sbecker59/statuspage-api-client-go/api/v1/statuspage"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_StatusEmbedConfigAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test StatusEmbedConfigAPIService GetPagesPageIdStatusEmbedConfig", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string

		resp, httpRes, err := apiClient.StatusEmbedConfigAPI.GetPagesPageIdStatusEmbedConfig(context.Background(), pageId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StatusEmbedConfigAPIService PatchPagesPageIdStatusEmbedConfig", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string

		resp, httpRes, err := apiClient.StatusEmbedConfigAPI.PatchPagesPageIdStatusEmbedConfig(context.Background(), pageId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StatusEmbedConfigAPIService PutPagesPageIdStatusEmbedConfig", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string

		resp, httpRes, err := apiClient.StatusEmbedConfigAPI.PutPagesPageIdStatusEmbedConfig(context.Background(), pageId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
