/*
Statuspage API

Testing PageAccessGroupComponentsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_PageAccessGroupComponentsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PageAccessGroupComponentsAPIService DeletePagesPageIdPageAccessGroupsPageAccessGroupIdComponents", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var pageAccessGroupId string

		resp, httpRes, err := apiClient.PageAccessGroupComponentsAPI.DeletePagesPageIdPageAccessGroupsPageAccessGroupIdComponents(context.Background(), pageId, pageAccessGroupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PageAccessGroupComponentsAPIService DeletePagesPageIdPageAccessGroupsPageAccessGroupIdComponentsComponentId", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var pageAccessGroupId string
		var componentId string

		resp, httpRes, err := apiClient.PageAccessGroupComponentsAPI.DeletePagesPageIdPageAccessGroupsPageAccessGroupIdComponentsComponentId(context.Background(), pageId, pageAccessGroupId, componentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PageAccessGroupComponentsAPIService GetPagesPageIdPageAccessGroupsPageAccessGroupIdComponents", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var pageAccessGroupId string

		resp, httpRes, err := apiClient.PageAccessGroupComponentsAPI.GetPagesPageIdPageAccessGroupsPageAccessGroupIdComponents(context.Background(), pageId, pageAccessGroupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PageAccessGroupComponentsAPIService PatchPagesPageIdPageAccessGroupsPageAccessGroupIdComponents", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var pageAccessGroupId string

		resp, httpRes, err := apiClient.PageAccessGroupComponentsAPI.PatchPagesPageIdPageAccessGroupsPageAccessGroupIdComponents(context.Background(), pageId, pageAccessGroupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PageAccessGroupComponentsAPIService PostPagesPageIdPageAccessGroupsPageAccessGroupIdComponents", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var pageAccessGroupId string

		resp, httpRes, err := apiClient.PageAccessGroupComponentsAPI.PostPagesPageIdPageAccessGroupsPageAccessGroupIdComponents(context.Background(), pageId, pageAccessGroupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PageAccessGroupComponentsAPIService PutPagesPageIdPageAccessGroupsPageAccessGroupIdComponents", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var pageAccessGroupId string

		resp, httpRes, err := apiClient.PageAccessGroupComponentsAPI.PutPagesPageIdPageAccessGroupsPageAccessGroupIdComponents(context.Background(), pageId, pageAccessGroupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
