/*
Statuspage API

Testing IncidentSubscribersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/sbecker59/statuspage-api-client-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_IncidentSubscribersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test IncidentSubscribersAPIService DeletePagesPageIdIncidentsIncidentIdSubscribersSubscriberId", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var incidentId string
		var subscriberId string

		resp, httpRes, err := apiClient.IncidentSubscribersAPI.DeletePagesPageIdIncidentsIncidentIdSubscribersSubscriberId(context.Background(), pageId, incidentId, subscriberId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IncidentSubscribersAPIService GetPagesPageIdIncidentsIncidentIdSubscribers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var incidentId string

		resp, httpRes, err := apiClient.IncidentSubscribersAPI.GetPagesPageIdIncidentsIncidentIdSubscribers(context.Background(), pageId, incidentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IncidentSubscribersAPIService GetPagesPageIdIncidentsIncidentIdSubscribersSubscriberId", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var incidentId string
		var subscriberId string

		resp, httpRes, err := apiClient.IncidentSubscribersAPI.GetPagesPageIdIncidentsIncidentIdSubscribersSubscriberId(context.Background(), pageId, incidentId, subscriberId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IncidentSubscribersAPIService PostPagesPageIdIncidentsIncidentIdSubscribers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var incidentId string

		resp, httpRes, err := apiClient.IncidentSubscribersAPI.PostPagesPageIdIncidentsIncidentIdSubscribers(context.Background(), pageId, incidentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IncidentSubscribersAPIService PostPagesPageIdIncidentsIncidentIdSubscribersSubscriberIdResendConfirmation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var incidentId string
		var subscriberId string

		httpRes, err := apiClient.IncidentSubscribersAPI.PostPagesPageIdIncidentsIncidentIdSubscribersSubscriberIdResendConfirmation(context.Background(), pageId, incidentId, subscriberId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
