/*
Statuspage API

Testing SubscribersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/sbecker59/statuspage-api-client-go/api/v1/statuspage"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_SubscribersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SubscribersAPIService DeletePagesPageIdSubscribersSubscriberId", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var subscriberId string

		resp, httpRes, err := apiClient.SubscribersAPI.DeletePagesPageIdSubscribersSubscriberId(context.Background(), pageId, subscriberId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubscribersAPIService GetPagesPageIdSubscribers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string

		resp, httpRes, err := apiClient.SubscribersAPI.GetPagesPageIdSubscribers(context.Background(), pageId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubscribersAPIService GetPagesPageIdSubscribersCount", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string

		resp, httpRes, err := apiClient.SubscribersAPI.GetPagesPageIdSubscribersCount(context.Background(), pageId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubscribersAPIService GetPagesPageIdSubscribersHistogramByState", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string

		resp, httpRes, err := apiClient.SubscribersAPI.GetPagesPageIdSubscribersHistogramByState(context.Background(), pageId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubscribersAPIService GetPagesPageIdSubscribersSubscriberId", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var subscriberId string

		resp, httpRes, err := apiClient.SubscribersAPI.GetPagesPageIdSubscribersSubscriberId(context.Background(), pageId, subscriberId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubscribersAPIService GetPagesPageIdSubscribersUnsubscribed", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string

		resp, httpRes, err := apiClient.SubscribersAPI.GetPagesPageIdSubscribersUnsubscribed(context.Background(), pageId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubscribersAPIService PatchPagesPageIdSubscribersSubscriberId", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var subscriberId string

		resp, httpRes, err := apiClient.SubscribersAPI.PatchPagesPageIdSubscribersSubscriberId(context.Background(), pageId, subscriberId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubscribersAPIService PostPagesPageIdSubscribers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string

		resp, httpRes, err := apiClient.SubscribersAPI.PostPagesPageIdSubscribers(context.Background(), pageId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubscribersAPIService PostPagesPageIdSubscribersReactivate", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string

		httpRes, err := apiClient.SubscribersAPI.PostPagesPageIdSubscribersReactivate(context.Background(), pageId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubscribersAPIService PostPagesPageIdSubscribersResendConfirmation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string

		httpRes, err := apiClient.SubscribersAPI.PostPagesPageIdSubscribersResendConfirmation(context.Background(), pageId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubscribersAPIService PostPagesPageIdSubscribersSubscriberIdResendConfirmation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string
		var subscriberId string

		httpRes, err := apiClient.SubscribersAPI.PostPagesPageIdSubscribersSubscriberIdResendConfirmation(context.Background(), pageId, subscriberId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubscribersAPIService PostPagesPageIdSubscribersUnsubscribe", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var pageId string

		httpRes, err := apiClient.SubscribersAPI.PostPagesPageIdSubscribersUnsubscribe(context.Background(), pageId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
